/**
 * AIの戦術判断を調整する上級者向け設定です。
 * 通常は game-balance.ts の5項目だけを変更してください。
 * AIの性格や試合テンポを細かく変えたい場合だけ、この値を調整します。
 */
export const AI_STRATEGY = {
  score: {
    win: 1_000_000,
    rankStep: 100_000,
    ownProgress: 620,
    rivalProgress: 510,
    rivalPressure: 120,
    smallMeteor: 18,
    largeMeteor: 34,
    capsuleMeteor: 15,
    activeShield: 26,
    boosterMove: 8,
    mobility: 3,
    freeForAllRivalAdvance: 800,
    freeForAllRivalFinish: 900_000,
  },
  pacing: {
    multiplayerWarningWithMeteor: 50,
    multiplayerWarningEmpty: 20,
    coordinatedThreatUnits: 2,
    coordinatedDefenseShortage: 30_000,
    delegatedThreatRisk: 320,
    duelWarningWithMeteor: 900,
    duelWarningEmpty: 350,
    overtimeStartsAfterRounds: 2,
    overtimeProgress: 22,
    classicRetreatPenalty: 260,
    itemRetreatPenalty: 170,
    earlyAdvanceBonus: 34,
    itemForwardTempo: 42,
  },
  difficulty: {
    easyChoiceWidth: 12,
    easyChoiceTolerance: 650,
    normalChoiceWidth: 7,
    normalChoiceTolerance: 240,
    easyImmediateThreatPenalty: 350,
    normalImmediateThreatPenalty: 30_000,
    hardImmediateThreatPenalty: 180_000,
    easyItemRetreatPenalty: 520,
    normalRetreatProofMargin: 260,
    easyDelegatedThreatRisk: 0,
    normalDelegatedThreatRisk: 120,
  },
  placement: {
    openingHarassment: 2_500,
    remoteHarassmentPerCell: 620,
    ownAdvance: 90,
    rivalSetback: 70,
    futureGate: 46,
    quietGate: 120,
  },
  items: {
    orbitMinimumGain: 4,
    pulseMobility: 14,
    blastMobility: 5,
    shieldLossPenalty: 150,
    pulseEscapeBonus: 760,
    pulseMeteorEscapeBonus: 100_000,
    duelItemCreativity: 11,
    useThresholdEasy: -4,
    useThresholdNormal: 2,
    useThresholdHard: 0,
    loadoutPersonality: {
      red: { shield: 2, booster: 8, holo: 0, orbit: 0, blast: 3, pulse: 0, recall: 0, gravity: 0 },
      blue: { shield: 0, booster: 0, holo: 5, orbit: 0, blast: 3, pulse: 8, recall: 0, gravity: 0 },
      green: { shield: 0, booster: 0, holo: 4, orbit: 9, blast: 0, pulse: 0, recall: 6, gravity: 0 },
      yellow: { shield: 8, booster: 2, holo: 0, orbit: 0, blast: 0, pulse: 0, recall: 12, gravity: 0 },
    },
    reserve: {
      shield: 22,
      booster: 24,
      holo: 20,
      orbit: 24,
      blast: 22,
      pulse: 22,
      recall: 18,
      gravity: 0,
    },
  },
} as const;
