export type ReleaseNote = {
  version: string;
  date: string;
  title: { ja: string; en: string };
  summary: { ja: string; en: string };
  details: { ja: readonly string[]; en: readonly string[] };
  tags: readonly ("BUG FIX" | "UI" | "SYSTEM" | "ASSET")[];
};

// 新しいバージョンを先頭へ追加。設定画面には先頭3件だけが表示されます。
export const RELEASE_NOTES = [
  { version:"1.0.65", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"案内とチャット表示を修正",en:"Fixed guidance and chat display"}, summary:{ja:"自由対戦中の案内とオンラインチャットの表示を整理。",en:"Refined free-play guidance and online chat presentation."}, details:{ja:["チュートリアルボタンの形を統一","チャット欄を右下へ配置"],en:["Unified the tutorial button shape","Moved chat to the lower right"]} },
  { version:"1.0.64", date:"2026-09-07", tags:["UI","BUG FIX"], title:{ja:"チュートリアル表示を改善",en:"Improved tutorial presentation"}, summary:{ja:"導線を統一し、CPUの行動を見やすく調整。",en:"Unified tutorial access and improved CPU action visibility."}, details:{ja:["案内表示を整理"],en:["Refined tutorial guidance"]} },
  { version:"1.0.63", date:"2026-09-07", tags:["SYSTEM","BUG FIX"], title:{ja:"練習CPUとEASYを調整",en:"Refined training and EASY CPU"}, summary:{ja:"案内中の動きとEASYの判断を安定化。",en:"Stabilized guided actions and EASY decisions."}, details:{ja:["分かりやすい判断を優先"],en:["Prioritizes understandable decisions"]} },
  { version:"1.0.62", date:"2026-09-07", tags:["SYSTEM"], title:{ja:"EASYのメテオ選択を調整",en:"Adjusted EASY meteor choices"}, summary:{ja:"EASYでは小メテオだけを使用するよう調整。",en:"EASY now uses small meteors only."}, details:{ja:["難易度ごとの特徴を明確化"],en:["Clarified the difficulty levels"]} },
  { version:"1.0.61", date:"2026-09-07", tags:["BUG FIX","SYSTEM"], title:{ja:"チュートリアルCPUを修正",en:"Fixed the tutorial CPU"}, summary:{ja:"練習を最後まで進められるよう調整。",en:"Training can now always be completed."}, details:{ja:["CPUの勝利条件を調整"],en:["Adjusted the CPU win condition"]} },
  { version:"1.0.60", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"チュートリアル開始確認を修正",en:"Fixed tutorial confirmation"}, summary:{ja:"各画面で開始確認がすぐ表示されるよう修正。",en:"Tutorial confirmation now appears immediately across screens."}, details:{ja:["開始確認の表示を安定化"],en:["Stabilized the start confirmation"]} },
  { version:"1.0.59", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"チュートリアル進行を調整",en:"Refined tutorial timing"}, summary:{ja:"説明と相手の行動が順番に進むよう調整。",en:"Tutorial guidance and opponent actions now proceed in sequence."}, details:{ja:["説明中は盤面を停止"],en:["Pauses the board during guidance"]} },
  { version:"1.0.58", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"チュートリアル入口を修正",en:"Fixed tutorial access"}, summary:{ja:"各準備画面からチュートリアルを開始可能に。",en:"Tutorial access is now available from preparation screens."}, details:{ja:["案内表現を統一"],en:["Unified guidance wording"]} },
  { version:"1.0.57", date:"2026-09-07", tags:["UI"], title:{ja:"案内文を調整",en:"Refined tutorial guidance"}, summary:{ja:"AEQRISの案内を自然な表現に調整。",en:"Refined AEQRIS tutorial guidance."}, details:{ja:["現在のルールを簡潔に案内"],en:["Presents the current rules concisely"]} },
  { version:"1.0.56", date:"2026-09-07", tags:["UI","BUG FIX"], title:{ja:"チュートリアル入口を全画面へ統一",en:"Unified tutorial access across screens"}, summary:{ja:"オンライン対戦中を除き、ホーム・対戦設定・通常対戦画面からすぐ開始確認を表示。",en:"Tutorial confirmation is now available from home, setup, and offline match screens."}, details:{ja:["確認文を「チュートリアルを開始しますか？」だけに簡略化","YESからチュートリアルへ直接移動","オフライン対戦画面の右上にも初心者ボタンを追加","オンライン待機室からは正常に退出して開始","進行中のオンライン対戦ではボタンを非表示"],en:["Simplified the confirmation prompt","Starts directly after YES","Added the beginner button to offline matches","Leaves online waiting rooms cleanly before training","Hides the button during active online matches"]} },
  { version:"1.0.55", date:"2026-09-07", tags:["UI","BUG FIX"], title:{ja:"チュートリアル導線を短縮",en:"Shortened the tutorial entry flow"}, summary:{ja:"初心者ボタンから確認後、対戦設定を挟まず直接チュートリアルを開始。",en:"The beginner button now starts the tutorial directly after one confirmation."}, details:{ja:["ボタンを押した場所で即座に開始確認を表示","YESから実戦形式チュートリアルへ直接移動","開いているマニュアルや設定が導線を妨げないよう整理"],en:["Shows confirmation immediately","Starts live-match training directly after YES","Closes overlapping Manual or Settings panels"]} },
  { version:"1.0.54", date:"2026-09-07", tags:["BUG FIX","UI","SYSTEM"], title:{ja:"実戦画面チュートリアルへ刷新",en:"Rebuilt tutorial on the live match UI"}, summary:{ja:"通常の対戦画面とゲーム性を保ったまま、AEQRISの説明と強調表示を重ねる方式へ変更。",en:"Tutorial guidance now overlays the real match UI without replacing or over-restricting gameplay."}, details:{ja:["専用の簡易盤を廃止し通常戦と同じ盤面・HUD・操作を使用","合法手を制限せず推奨手だけを強調","前進・横移動・後退や爆風結果に応じて説明を分岐","右上の遊び方と初心者導線を並べて配置","ボーナス移動の説明を遊び方・マニュアル・詳細ガイドへ追加","全モード・人数構成63試合のシミュレーションを完走"],en:["Uses the real board, HUD, and controls","Keeps every legal action available while highlighting suggestions","Adapts guidance to movement and blast outcomes","Places Tutorial beside the top-right Manual control","Documents the last-meteor bonus move throughout the guides","Completed 63 simulated matches across all supported modes"]} },
  { version:"1.0.53", date:"2026-09-07", tags:["UI","SYSTEM"], title:{ja:"分岐型チュートリアルを追加",en:"Added an adaptive tutorial"}, summary:{ja:"AEQRISの案内で移動・爆風・大メテオ・CORE到達を実際に体験できる初心者訓練を追加。",en:"Added hands-on AEQRIS training for movement, blast travel, large meteors, and CORE arrival."}, details:{ja:["あそびかた横の初心者マークから開始","前進・横移動など最初の選択に応じて案内を分岐","小メテオの斜め爆風移動と大メテオを実操作","練習CPUはプレイヤーより先にゴールしない","完了後はホーム画面へ安全に復帰"],en:["Starts from the beginner mark beside How to Play","Adapts guidance to the player's opening move","Provides hands-on small and large meteor practice","Training CPU never reaches the CORE first","Returns safely to the home screen"]} },
  { version:"1.0.52", date:"2026-09-02", tags:["BUG FIX","UI"], title:{ja:"PULSE脱出判断と規約名を改善",en:"Improved PULSE escape and policy naming"}, summary:{ja:"CPUがメテオ爆風によるPULSE脱出も判断し、統合ページ名を利用規約へ変更。",en:"CPU now considers meteor-blast PULSE escapes; the combined legal page has a clearer name."}, details:{ja:["通常メテオによるPULSE範囲外への脱出を優先評価","BLASTとメテオの有効な脱出手を同じ判断候補で比較","サイトポリシーの表示名を利用規約へ変更","プライバシー方針は利用規約内に維持"],en:["Prioritizes valid meteor-blast escapes from PULSE","Compares BLAST and meteor escape options","Renamed the combined legal page","Keeps privacy policy within the terms page"]} },
  { version:"1.0.51", date:"2026-09-02", tags:["BUG FIX","UI"], title:{ja:"サイトポリシー統合とアイテムAI改善",en:"Unified policy and improved item AI"}, summary:{ja:"法務ページを統合し、PULSE拘束時と1対1アイテム戦のCPU判断を改善。",en:"Unified policy pages and improved duel item AI under PULSE."}, details:{ja:["プライバシーと利用規約をサイトポリシーへ統合","設定内の不要なリンクを削除","PULSE拘束中の無駄なBOOSTER使用を禁止","BLASTによるPULSE脱出を優先評価","設定ヘッダー上部の表示漏れを修正"],en:["Unified privacy and terms into Site Policy","Removed obsolete Settings links","Prevents wasted BOOSTER use while PULSE-locked","Prioritizes BLAST escape from PULSE","Fixed content showing above the Settings header"]} },
  { version:"1.0.50", date:"2026-09-02", tags:["BUG FIX","UI"], title:{ja:"更新履歴のスクロールを修正",en:"Fixed release-history scrolling"}, summary:{ja:"画面の高さにかかわらず、更新履歴を最後までスクロールできるよう修正。",en:"Release history can now scroll fully at every viewport height."}, details:{ja:["対戦画面専用のスクロール固定から文書ページを除外","PC・スマホで縦スクロールを維持"],en:["Excluded document pages from the battle viewport lock","Preserved vertical scrolling on desktop and mobile"]} },
  { version:"1.0.49", date:"2026-09-01", tags:["SYSTEM","UI"], title:{ja:"更新履歴を追加",en:"Release history added"}, summary:{ja:"最新3件の更新内容と、全履歴を確認できる画面を追加。",en:"Added recent updates and a complete release-history page."}, details:{ja:["設定画面に最新3件の更新内容を表示","「すべて見る」から過去の更新履歴を確認可能","更新内容を1ファイルで管理できる構成へ整理"],en:["Shows the three latest updates in Settings","Adds a complete history page","Centralizes release notes in one file"]} },
  { version:"1.0.48", date:"2026-08-30", tags:["ASSET","UI"], title:{ja:"ファビコンの視認性を改善",en:"Improved favicon visibility"}, summary:{ja:"白背景の公式シンボルを採用し、小さい表示でも見やすく調整。",en:"Uses the official symbol on white for clearer small-size display."}, details:{ja:["白背景版のシンボルへ変更","ブラウザタブでの識別性を改善"],en:["Switched to the white-background symbol","Improved browser-tab recognition"]} },
  { version:"1.0.47", date:"2026-08-30", tags:["BUG FIX","ASSET"], title:{ja:"ロゴ表示の遅れを解消",en:"Removed logo display delay"}, summary:{ja:"ロゴを事前読込し、画面表示時の一瞬の遅れを解消。",en:"Preloads logos to remove the brief display delay."}, details:{ja:["タイトル・シンボルロゴを事前読込","不要なフェード待ちを削除"],en:["Preloads title and symbol logos","Removed unnecessary fade delay"]} },
  { version:"1.0.46", date:"2026-08-30", tags:["ASSET"], title:{ja:"公式シンボルをファビコンへ反映",en:"Official symbol favicon"}, summary:{ja:"仮アイコンから正式な記号ロゴへ変更。",en:"Replaced the provisional icon with the official symbol."}, details:{ja:["サイトのファビコンを正式ロゴへ統一"],en:["Unified the favicon with the official mark"]} },
  { version:"1.0.45", date:"2026-08-30", tags:["ASSET"], title:{ja:"専用ファビコンを追加",en:"Added a custom favicon"}, summary:{ja:"ブラウザタブ用の専用アイコンを追加。",en:"Added a dedicated browser-tab icon."}, details:{ja:["汎用アイコンから専用アイコンへ変更"],en:["Replaced the generic browser icon"]} },
  { version:"1.0.44", date:"2026-08-30", tags:["BUG FIX","UI"], title:{ja:"PC対戦画面の重なりを修正",en:"Fixed desktop battle overlap"}, summary:{ja:"盤面・操作欄・下部バーを分離し、スクロールなしで収まるよう調整。",en:"Separated board, controls, and footer for a no-scroll desktop layout."}, details:{ja:["メテオ配置欄と盤面の重なりを解消","下部バー用の表示領域を確保","低い画面でも操作できるよう調整"],en:["Cleared meteor controls from the board","Reserved space for the footer","Improved short-screen operation"]} },
  { version:"1.0.43", date:"2026-08-30", tags:["BUG FIX","UI"], title:{ja:"所持品表示を整理",en:"Refined loadout display"}, summary:{ja:"BOOSTERなどの名称と所持数が重ならない2段表示へ変更。",en:"Separated item labels and counts into two rows."}, details:{ja:["アイテム名と数字の重なりを修正","限られた幅での視認性を改善"],en:["Fixed item label/count overlap","Improved narrow-width readability"]} },
  { version:"1.0.42", date:"2026-08-30", tags:["BUG FIX","UI"], title:{ja:"メテオ操作欄の位置を修正",en:"Fixed meteor-control placement"}, summary:{ja:"配置操作が盤面を覆わないようレイアウトを修正。",en:"Adjusted placement controls so they no longer cover the board."}, details:{ja:["誤操作につながる表示の重なりを解消"],en:["Removed overlap that could cause unintended input"]} },
  { version:"1.0.41", date:"2026-08-30", tags:["UI"], title:{ja:"全年齢向けに視認性を向上",en:"Improved all-ages readability"}, summary:{ja:"主要な文字とボタンを大きくし、操作しやすさを改善。",en:"Enlarged key text and controls for easier play."}, details:{ja:["主要ボタンの押しやすさを改善","案内文字のサイズを拡大"],en:["Improved primary button accessibility","Increased guidance text size"]} },
] as const satisfies readonly ReleaseNote[];

export const LATEST_RELEASE_NOTES = RELEASE_NOTES.slice(0, 3);
