export type ReleaseNote = {
  version: string;
  date: string;
  title: { ja: string; en: string };
  summary: { ja: string; en: string };
  details: { ja: readonly string[]; en: readonly string[] };
  tags: readonly ("BUG FIX" | "UI" | "SYSTEM" | "ASSET")[];
};

// 新しいバージョンを先頭へ追加。設定画面には先頭3件だけが表示されます。
export const RELEASE_NOTES = [
  { version: "1.0.103", date: "2026-10-10", tags: ["BUG FIX", "UI"], title: { ja: "オンラインルームのイベント設定を改善", en: "Improved room event settings" }, summary: { ja: "PCの待機ルームで盤面イベント欄が細く崩れる問題を修正しました。", en: "Fixed cramped field-event controls in desktop online lobbies." }, details: { ja: ["イベント欄を全幅にし、利用できる幅に応じてボタンと周期設定を整列"], en: ["Event controls span the room and arrange buttons and intervals to fit the available width"] } },
  { version: "1.0.102", date: "2026-10-10", tags: ["BUG FIX", "UI"], title: { ja: "PC対戦画面の盤面位置を安定化", en: "Stable desktop board layout" }, summary: { ja: "カーソル予告やメテオ配置への切り替えで盤面が動く問題を修正しました。", en: "Fixed board movement when showing hover previews or meteor placement controls." }, details: { ja: ["操作欄の領域を常に確保し、盤面の位置とサイズを維持"], en: ["Action space stays reserved to keep board position and size stable"] } },
  { version: "1.0.101", date: "2026-10-10", tags: ["SYSTEM", "UI"], title: { ja: "惑星イベントを調整", en: "Planetary event refinements" }, summary: { ja: "重力・ORBIT・間欠泉の配置と、暴風の移動量を調整しました。", en: "Refined gravity, orbit and geyser placement, and increased gale movement." }, details: { ja: ["重力中心はCOREから3マス以上離れた場所に出現", "ORBITはCORE直近のリングを対象外に変更", "間欠泉は間隔を保ちながらランダムな4か所に配置", "追い風を暴風に変更し、最大2マス移動・短く幅広い矢印に変更"], en: ["Gravity centers stay at least 3 cells from CORE", "Orbit excludes the innermost ring", "Four randomly scattered, spaced geysers", "Wind renamed Gale: up to two cells of movement, with shorter, broader arrows"] } },
  { version: "1.0.100", date: "2026-10-10", tags: ["SYSTEM", "UI"], title: { ja: "重力異常の引力と予告を更新", en: "Gravity anomaly update" }, summary: { ja: "重力の中心がランダムになり、近い探査機ほど強く引き寄せられます。", en: "Gravity now pulls toward a random center, with stronger attraction nearby." }, details: { ja: ["中心から2マス以内は最大2マス、3〜5マスは1マス移動", "2巡前から中心と強弱の範囲を紫で表示", "ランク戦の中央重力は変更なし"], en: ["Up to 2 steps within 2 cells; 1 step within 3–5 cells", "Purple center and strength ranges appear two rounds ahead", "Ranked central gravity is unchanged"] } },
  { version: "1.0.99", date: "2026-10-10", tags: ["SYSTEM", "BUG FIX"], title: { ja: "ワープイベントとCPU判断の改善", en: "Warp gates and CPU improvements" }, summary: { ja: "内周と外周をつなぐワープを追加。ORBITはイベント限定になりました。", en: "Added warp gates linking inner and outer regions. ORBIT is now event-only." }, details: { ja: ["ワープは青白く発光し、周期ごとに空きマスへ移動", "機体や配置物の下には出現せず、移動先予告はなし", "CPUの自滅的なPULSE配置と次手ゴールの見落としを改善", "多人数戦で後続プレイヤーに防御を任せる判断を調整"], en: ["Blue-white gates relocate to free cells periodically", "No placement under probes or objects, and no location forecast", "Improved CPU PULSE safety and immediate-finish detection", "Improved multiplayer defensive delegation"] } },
  { version: "1.0.98", date: "2026-10-10", tags: ["SYSTEM"], title: { ja: "イベントの連携順を調整", en: "Updated event resolution order" }, summary: { ja: "同時発動は追い風 → ORBIT → 間欠泉 → 中央重力の順になりました。", en: "Simultaneous events now resolve as wind → orbit → geyser → gravity." }, details: { ja: ["風でリングに乗り、回転先の間欠泉を使って進める順番に調整", "途中でCOREへ到達した場合は、その時点で到達を確定"], en: ["Use wind to board a rotating ring, then catch a steam vent at the destination", "Reaching CORE takes priority over later events"] } },
  { version: "1.0.97", date: "2026-10-10", tags: ["UI"], title: { ja: "間欠泉と風の予告を調整", en: "Refined geyser and wind warnings" }, summary: { ja: "噴出口が塞がれているか見分けやすくしました。", en: "Covered vents are easier to distinguish." }, details: { ja: ["噴出予告は赤い警戒模様、塞がれた噴出口は白い縁で表示", "噴出口の状態に合わせて周囲の予告も切り替え", "風向きの矢印を太く調整"], en: ["Red warning patterns for open vents, white rims for covered vents", "Nearby forecasts reflect the vent state", "Wider wind-direction arrows"] } },
  { version: "1.0.96", date: "2026-10-10", tags: ["UI"], title: { ja: "イベント予告を見やすく整理", en: "Clearer event forecasts" }, summary: { ja: "複数の予告が重なっても盤面を読み取りやすくしました。", en: "Overlapping forecasts leave the board easier to read." }, details: { ja: ["発動が近づくほど予告を強調", "風は盤端、重力はCORE周辺に予告を表示", "イベントのアイコンと説明を統一", "対戦設定から効果と発動順を確認可能"], en: ["Forecast emphasis increases as activation approaches", "Wind forecasts sit near the edge; gravity stays around CORE", "Consistent event icons and explanations", "Event effects and resolution order available in match setup"] } },
  { version: "1.0.95", date: "2026-10-10", tags: ["UI", "BUG FIX"], title: { ja: "スマホの操作と所持欄を改善", en: "Improved mobile controls and inventory" }, summary: { ja: "盤面を1タップで操作でき、所持アイテムが枠内に収まるよう調整しました。", en: "Board actions now take one tap, and inventory stays within player cards." }, details: { ja: ["アイテムアイコンを統一した線画に変更", "PCはホバーで移動結果を予告", "対象を点線、移動先を白い実線で表示"], en: ["Consistent line-art item icons", "Mouse hover previews action outcomes", "Dashed targets and solid white destinations"] } },

  { version: "1.0.94", date: "2026-10-10", tags: ["UI"], title: { ja: "持ち込み装備のデザインを刷新", en: "Refined equipment loadout design" }, summary: { ja: "装備を横長パネル3段に並べ、アイコンと説明を見やすくしました。", en: "Equipment now appears in three horizontal rows with aligned icons and descriptions." }, details: { ja: ["左にアイコン、右に名前・説明・効果の数値を統一配置", "各装備を開いて詳しい効果を確認可能", "装備カラーと選択ボタンのデザインを統一"], en: ["Icons on the left, names and effect information on the right", "Expand each item for its full description", "Consistent equipment colors and selection controls"] } },

  { version: "1.0.93", date: "2026-10-10", tags: ["UI", "BUG FIX"], title: { ja: "持ち込み画面とイベント表示を整理", en: "Clearer loadout and event displays" }, summary: { ja: "アイテムの説明を確認しやすくし、イベント表示をコンパクトにしました。", en: "Item descriptions are easier to compare and event information takes less space." }, details: { ja: ["PCでは選んだアイテムの説明を横並びで表示", "スマホでアイテムの旗を押して説明を切り替え可能", "イベント詳細は必要なときに開いて確認", "説明と選択ボタンの重なりを防止"], en: ["Compare selected item descriptions side by side on desktop", "Tap item flags to switch descriptions on phones", "Open event details when needed", "Descriptions and selection controls no longer overlap"] } },
  { version: "1.0.92", date: "2026-10-10", tags: ["SYSTEM"], title: { ja: "イベントに合わせて盤面サイズを調整", en: "Board sizes adapt to field events" }, summary: { ja: "イベント1種類では11×11以上、複数では13×13以上の盤面になります。", en: "One event uses an 11×11 or larger board; multiple events use 13×13 or larger." }, details: { ja: ["イベント選択時に盤面サイズを自動調整", "15×15の盤面も選択可能"], en: ["Board size adjusts automatically when selecting events", "15×15 remains available"] } },
  { version: "1.0.91", date: "2026-10-10", tags: ["SYSTEM", "UI"], title: { ja: "間欠泉を利用する駆け引きを拡張", en: "Steam vents now preserve cover" }, summary: { ja: "間欠泉の蒸気で配置物が壊れなくなりました。", en: "Geyser steam now leaves placed objects intact." }, details: { ja: ["メテオを移動先に置くことで、蒸気による移動を防止", "NORMAL・HARDのCPUが発動直前のイベント予告を考慮", "追い風の方向を示す矢印を見やすく調整", "オンラインで囲まれた機体がメテオ配置へ進めない問題を修正"], en: ["Meteors can stop probes from being pushed by steam", "NORMAL and HARD consider imminent event forecasts", "Improved visibility of wind direction arrows", "Surrounded online probes can proceed to meteor placement"] } },
  { version: "1.0.90", date: "2026-10-10", tags: ["UI", "BUG FIX", "SYSTEM"], title: { ja: "盤面イベントの設定と演出を改善", en: "Improved field-event settings and effects" }, summary: { ja: "イベントごとに発動周期を選べるようになりました。", en: "Each field event now has its own interval setting." }, details: { ja: ["重力を紫の渦、追い風を方向に沿って流れる砂塵で表現", "イベントのORBIT対象タイルを緑色で表示", "複数イベントの演出と機体移動を順番に表示", "項目が少ない選択画面を上下中央へ配置"], en: ["Purple gravity vortices and directional sand gusts", "Green tiles identify event ORBIT rings", "Event effects and probe movement play in sequence", "Short selection screens are vertically centered"] } },
  { version: "1.0.89", date: "2026-10-10", tags: ["UI", "BUG FIX"], title: { ja: "あそびかたの重なりを修正", en: "Fixed overlapping guide sections" }, summary: { ja: "ルール・イベント・アイテムの説明を読みやすく整理しました。", en: "Improved the layout of rules, events and item descriptions." }, details: { ja: ["文字サイズに合わせて説明欄の高さを確保", "スマートフォンの案内見出しと切り替えボタンを整理", "手順カード・爆風の図・イベント選択ボタンの高さを統一", "世界観の本文を読みやすい大きさに調整"], en: ["Guide sections grow with text size", "Reorganized mobile guide headings and tabs", "Aligned turn cards, blast diagrams and event buttons", "Improved readability of world descriptions"] } },
  { version: "1.0.88", date: "2026-10-10", tags: ["UI", "BUG FIX"], title: { ja: "対戦設定とイベント表示を整理", en: "Clearer setup and field events" }, summary: { ja: "イベントをON/OFFボタンで選択でき、PCの設定画面を見やすくしました。", en: "Choose events with clear toggle buttons in a roomier desktop setup." }, details: { ja: ["見出し・本文・管制表示の書体を整理", "CPUの強さの説明を選択欄の下へ配置", "盤面イベントの説明をあそびかたに追加", "探査機の番号表示を整理し、プレイヤー帯の機体の比率を修正", "チュートリアル後にCPU対戦の設定へ進めるよう変更", "EASY・NORMALの序盤の配置判断を調整"], en: ["Refined typography for headings, text and telemetry", "Difficulty descriptions now sit below the selector", "Added field-event explanations to the manual", "Removed probe numbers and restored portrait proportions", "Tutorial completion can open CPU match setup", "Adjusted EASY and NORMAL opening placements"] } },
  { version: "1.0.87", date: "2026-10-10", tags: ["BUG FIX", "UI"], title: { ja: "対戦の見やすさと操作を改善", en: "Clearer matches and easier controls" }, summary: { ja: "アイテム説明・遊び方・チーム表示を見やすくし、スマートフォンの操作確認を追加。", en: "Improved item descriptions, rules and team displays, with action previews on phones." }, details: { ja: ["アイテムの旗を選んで効果を確認可能", "メテオの爆風範囲とボーナス移動を図と文章で案内", "機体番号と味方同士の並びでチームを識別", "複数イベントの予告をコンパクトに表示", "チュートリアルの重複する案内を整理", "NORMALの序盤は前進と布石を重視"], en: ["Select an item flag to read its effect", "Illustrated blast ranges and bonus-move guidance", "Probe numbers and grouped teammates make teams easier to identify", "Compact forecasts for multiple events", "Streamlined tutorial guidance", "NORMAL favors progress and preparation in the opening"] } },
  { version: "1.0.86", date: "2026-09-29", tags: ["BUG FIX"], title: { ja: "待機ルームとCPU判断を修正", en: "Fixed lobby settings and CPU decisions" }, summary: { ja: "参加・観戦・席交換の整合性と、CPUの難易度差を改善。", en: "Improved room membership, seat changes and CPU difficulty separation." }, details: { ja: ["参加人数に応じてCPU数と盤面サイズを調整", "席交換とCPU難易度を対戦開始時にも保持", "EASYのメテオ配置が過度に正確になる不具合を修正"], en: ["Adjusts CPU counts and board sizes to room membership", "Preserves exchanged seats and CPU difficulty when starting", "Fixed overly precise EASY meteor placement"] } },
  { version: "1.0.85", date: "2026-09-18", tags: ["BUG FIX", "UI"], title: { ja: "待機ルームの表示を修正", en: "Fixed waiting-room layout" }, summary: { ja: "スマートフォンでCPU設定と対戦開始ボタンが重なる不具合を修正。", en: "Fixed overlapping CPU settings and start buttons on phones." }, details: { ja: ["小さい画面でもメンバーと各操作をスクロールして確認可能"], en: ["Keeps members and room controls accessible by scrolling on small screens"] } },
  { version: "1.0.83", date: "2026-09-14", tags: ["UI"], title: { ja: "音楽の公開準備", en: "Preparing music for release" }, summary: { ja: "BGMと音楽設定を一時休止。効果音は引き続き利用可能。", en: "Temporarily disabled BGM and music controls. Sound effects remain available." }, details: { ja: ["BGM音量と曲選択を非表示"], en: ["Hidden BGM volume and track selection"] } },
  { version: "1.0.82", date: "2026-09-11", tags: ["BUG FIX"], title: { ja: "チーム結果と音量表示を修正", en: "Fixed team results and volume controls" }, summary: { ja: "英語の勝利チーム表示と、操作バーの音量表示を修正。", en: "Restored winning team names in English and aligned volume sliders with their displayed values." }, details: { ja: ["通常・アイテムのチーム戦で英語表示にも勝利チームを表示", "共通バーと設定画面の音量を1刻みで統一"], en: ["Shows the winning team in both classic and item team battles", "Uses one-percent volume steps across the toolbar and Settings"] } },
  { version: "1.0.81", date: "2026-09-11", tags: ["BUG FIX", "UI"], title: { ja: "対戦準備画面の重なりを修正", en: "Fixed overlapping setup controls" }, summary: { ja: "小さい画面で案内ボタンと見出しが重ならないよう調整。", en: "Separated help controls from headings on small screens." }, details: { ja: ["チュートリアルとあそびかたの操作スペースを確保"], en: ["Reserved space for tutorial and guide controls"] } },
  { version: "1.0.80", date: "2026-09-08", tags: ["ASSET", "SYSTEM"], title: { ja: "端末別アイコンに対応", en: "Added platform-specific icons" }, summary: { ja: "ブラウザとスマートフォン向けのアイコンを整備。", en: "Updated icons for browsers and mobile devices." }, details: { ja: ["iPhone・iPadとAndroid向けのホーム画面アイコンに対応"], en: ["Added home-screen icons for iPhone, iPad and Android"] } },
  { version:"1.0.79", date:"2026-09-08", tags:["BUG FIX","UI","SYSTEM"], title:{ja:"通知位置と全画面の整合性を改善",en:"Improved notification placement and interface consistency"}, summary:{ja:"チャット通知を右下へ固定し、翻訳・時刻表示・チュートリアル案内の食い違いを修正。",en:"Anchored chat notifications to the lower right and aligned translations, schedules, and tutorial guidance."}, details:{ja:["新着チャットを共通操作バーの上、右下へ固定","ランク戦の日本語・英語スケジュールを統一","チュートリアルの大メテオ案内を正しい順序で表示"],en:["Anchored new-message alerts above the lower-right control bar","Aligned Japanese and English ranked schedules","Restored the large-meteor tutorial step in the correct sequence"]} },
  { version:"1.0.78", date:"2026-09-08", tags:["UI","SYSTEM"], title:{ja:"英語表示を全画面へ拡張",en:"Expanded English support across the site"}, summary:{ja:"お問い合わせ、チュートリアル、対戦画面、待機ルーム、各案内ページの表示言語を統一。",en:"Unified language switching across contact, tutorial, matches, rooms, and information pages."}, details:{ja:["チュートリアル全文を日英対応","不具合報告フォームと送信結果を日英対応","対戦HUD・所持欄・チャット・オンライン待機ルームを日英対応","遊び方・アイテム一覧・更新履歴・利用規約を端末の表示言語に連動"],en:["Added full Japanese and English tutorial copy","Localized the contact form and submission results","Localized match HUD, inventory, chat, and online rooms","Linked the guide, item list, release history, and policy pages to the saved display language"]} },
  { version:"1.0.77", date:"2026-09-08", tags:["BUG FIX","SYSTEM"], title:{ja:"CPUのメテオ配置停止を修正",en:"Fixed stalled CPU meteor placement"}, summary:{ja:"手持ちにメテオがある限り、CPUが対戦を止めずに配置。",en:"CPU players now place a meteor whenever one remains available."}, details:{ja:["評価の低い配置でもパスより優先","小メテオがないEASYは大メテオで続行"],en:["Prioritizes any legal placement over passing","EASY uses a large meteor when no small meteor remains"]} },
  { version:"1.0.76", date:"2026-09-08", tags:["BUG FIX"], title:{ja:"CPU手番中の盤面操作を修正",en:"Fixed board input during CPU turns"}, summary:{ja:"チュートリアル自由対戦中の操作対象を正しく制限。",en:"Corrected input ownership during tutorial free play."}, details:{ja:["CPUの移動・メテオ配置中は盤面入力を無効化"],en:["Disables player board input during CPU movement and meteor placement"]} },
  { version:"1.0.75", date:"2026-09-08", tags:["UI","SYSTEM"], title:{ja:"オンライン待機ルームを改善",en:"Improved the online waiting room"}, summary:{ja:"AI設定とチャットをコンパクトで安全な操作へ調整。",en:"Refined AI settings and chat for safer, more compact operation."}, details:{ja:["AI難易度を人数操作の左側へ移動","10回送信後に10秒間のチャット待機を追加","新着チャットを右下へ表示","メンバー入れ替えをルームリーダー限定に変更","更新履歴を別タブで表示"],en:["Moved AI difficulty to the left of member count controls","Adds a 10-second chat cooldown after ten messages","Shows new chat previews at the lower right","Restricts member swaps to the room leader","Opens release history in a separate tab"]} },
  { version:"1.0.74", date:"2026-09-08", tags:["BUG FIX","SYSTEM"], title:{ja:"オンライン戦の安定性を改善",en:"Improved online match stability"}, summary:{ja:"ホスト端末で対戦が止まる問題を軽減。",en:"Reduced match stalls on the host device."}, details:{ja:["AIの無効なメテオ配置による進行停止を防止","チーム変更をルームリーダー限定に変更"],en:["Prevents invalid AI meteor placement from stalling a match","Restricts team changes to the room leader"]} },
  { version:"1.0.73", date:"2026-09-07", tags:["UI","SYSTEM"], title:{ja:"オンラインルームを拡張",en:"Expanded online rooms"}, summary:{ja:"最大10人の参加と、全員に伝わる対戦設定表示へ改善。",en:"Online rooms now support 10 members and shared match settings."}, details:{ja:["対戦席は最大4人","5人目以降は自動で観戦","観戦者もルームチャットに参加可能","チーム戦・アイテム戦・盤面・CPU人数を全員へ同期表示","閉じているチャットへ未読件数と新着吹き出しを表示"],en:["Up to four active players","Members after the fourth automatically spectate","Spectators can use room chat","Team, item, board, and CPU settings are visible to everyone","Shows unread counts and message previews while chat is closed"]} },
  { version:"1.0.72", date:"2026-09-07", tags:["BUG FIX","UI","SYSTEM"], title:{ja:"対戦ルールと進行を改善",en:"Improved battle rules and flow"}, summary:{ja:"アイテム操作とボーナス行動、オンライン対戦後の流れを改善。",en:"Improved item controls, bonus actions, and the online post-match flow."}, details:{ja:["SHIELDは爆風移動を1マス軽減","ORBITに180度回転を追加","ボーナス行動で移動かアイテムを選択可能","配置しないを選択欄の最後へ移動","オンライン対戦後はマッチルームへ復帰"],en:["SHIELD reduces blast movement by one cell","Added 180-degree ORBIT rotation","Bonus actions can use movement or an item","Moved skip placement to the end","Returns online players to the match room after each battle"]} },
  { version:"1.0.71", date:"2026-09-07", tags:["SYSTEM","UI"], title:{ja:"複数人戦の進行を改善",en:"Improved multiplayer flow"}, summary:{ja:"対戦終了を短縮し、オンラインルーム内の導線を整理。",en:"Shortened match endings and simplified online room navigation."}, details:{ja:["AIだけの対戦継続を省略","残り順位を自動確定","オンラインルーム内のチュートリアルを非表示"],en:["Skips AI-only match continuation","Automatically determines remaining ranks","Hides tutorial access inside online rooms"]} },
  { version:"1.0.69", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"対戦表示を安定化",en:"Stabilized match presentation"}, summary:{ja:"盤面とCORE到達表示、各画面の操作ボタンを改善。",en:"Improved the board, CORE arrival flow, and screen controls."}, details:{ja:["操作中の盤面サイズを固定","チュートリアルの完了表示を修正","CORE到達後の待ち時間を調整","閉じるボタンの位置を統一"],en:["Keeps the board size fixed during actions","Fixed tutorial completion","Adjusted the delay after reaching the CORE","Aligned close controls consistently"]} },
  { version:"1.0.68", date:"2026-09-07", tags:["SYSTEM","UI"], title:{ja:"可変レイアウトを強化",en:"Improved adaptive layout"}, summary:{ja:"画面や文字の大きさに合わせて盤面が自動調整されるよう改善。",en:"The board now adapts to the available screen and text size."}, details:{ja:["操作欄を含む表示領域へ自動追従"],en:["Adapts to the play area and action controls"]} },
  { version:"1.0.67", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"通常戦の盤面位置を修正",en:"Fixed classic board alignment"}, summary:{ja:"通常戦の盤面を上下中央へ正確に配置。",en:"Precisely centered the classic board vertically."}, details:{ja:["画面上下の余白を均等化"],en:["Balanced the space above and below the board"]} },
  { version:"1.0.66", date:"2026-09-07", tags:["UI"], title:{ja:"盤面の上下余白を調整",en:"Adjusted board spacing"}, summary:{ja:"通常戦とアイテム戦に合わせて盤面位置を調整。",en:"Refined board placement for classic and item matches."}, details:{ja:["画面サイズ別の余白を調整"],en:["Adjusted spacing by screen size"]} },
  { version:"1.0.65", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"案内とチャット表示を修正",en:"Fixed guidance and chat display"}, summary:{ja:"自由対戦中の案内とオンラインチャットの表示を整理。",en:"Refined free-play guidance and online chat presentation."}, details:{ja:["チュートリアルボタンの形を統一","チャット欄を右下へ配置"],en:["Unified the tutorial button shape","Moved chat to the lower right"]} },
  { version:"1.0.64", date:"2026-09-07", tags:["UI","BUG FIX"], title:{ja:"チュートリアル表示を改善",en:"Improved tutorial presentation"}, summary:{ja:"導線を統一し、CPUの行動を見やすく調整。",en:"Unified tutorial access and improved CPU action visibility."}, details:{ja:["案内表示を整理"],en:["Refined tutorial guidance"]} },
  { version:"1.0.63", date:"2026-09-07", tags:["SYSTEM","BUG FIX"], title:{ja:"練習CPUとEASYを調整",en:"Refined training and EASY CPU"}, summary:{ja:"案内中の動きとEASYの判断を安定化。",en:"Stabilized guided actions and EASY decisions."}, details:{ja:["分かりやすい判断を優先"],en:["Prioritizes understandable decisions"]} },
  { version:"1.0.62", date:"2026-09-07", tags:["SYSTEM"], title:{ja:"EASYのメテオ選択を調整",en:"Adjusted EASY meteor choices"}, summary:{ja:"EASYでは小メテオだけを使用するよう調整。",en:"EASY now uses small meteors only."}, details:{ja:["難易度ごとの特徴を明確化"],en:["Clarified the difficulty levels"]} },
  { version:"1.0.61", date:"2026-09-07", tags:["BUG FIX","SYSTEM"], title:{ja:"チュートリアルCPUを修正",en:"Fixed the tutorial CPU"}, summary:{ja:"練習を最後まで進められるよう調整。",en:"Training can now always be completed."}, details:{ja:["CPUの勝利条件を調整"],en:["Adjusted the CPU win condition"]} },
  { version:"1.0.60", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"チュートリアル開始確認を修正",en:"Fixed tutorial confirmation"}, summary:{ja:"各画面で開始確認がすぐ表示されるよう修正。",en:"Tutorial confirmation now appears immediately across screens."}, details:{ja:["開始確認の表示を安定化"],en:["Stabilized the start confirmation"]} },
  { version:"1.0.59", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"チュートリアル進行を調整",en:"Refined tutorial timing"}, summary:{ja:"説明と相手の行動が順番に進むよう調整。",en:"Tutorial guidance and opponent actions now proceed in sequence."}, details:{ja:["説明中は盤面を停止"],en:["Pauses the board during guidance"]} },
  { version:"1.0.58", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"チュートリアル入口を修正",en:"Fixed tutorial access"}, summary:{ja:"各準備画面からチュートリアルを開始可能に。",en:"Tutorial access is now available from preparation screens."}, details:{ja:["案内表現を統一"],en:["Unified guidance wording"]} },
  { version:"1.0.57", date:"2026-09-07", tags:["UI"], title:{ja:"案内文を調整",en:"Refined tutorial guidance"}, summary:{ja:"AEQRISの案内を自然な表現に調整。",en:"Refined AEQRIS tutorial guidance."}, details:{ja:["現在のルールを簡潔に案内"],en:["Presents the current rules concisely"]} },
  { version:"1.0.56", date:"2026-09-07", tags:["UI","BUG FIX"], title:{ja:"チュートリアル入口を全画面へ統一",en:"Unified tutorial access across screens"}, summary:{ja:"オンライン対戦中を除き、ホーム・対戦設定・通常対戦画面からすぐ開始確認を表示。",en:"Tutorial confirmation is now available from home, setup, and offline match screens."}, details:{ja:["確認文を「チュートリアルを開始しますか？」だけに簡略化","YESからチュートリアルへ直接移動","オフライン対戦画面の右上にも初心者ボタンを追加","オンライン待機室からは正常に退出して開始","進行中のオンライン対戦ではボタンを非表示"],en:["Simplified the confirmation prompt","Starts directly after YES","Added the beginner button to offline matches","Leaves online waiting rooms cleanly before training","Hides the button during active online matches"]} },
  { version:"1.0.55", date:"2026-09-07", tags:["UI","BUG FIX"], title:{ja:"チュートリアル導線を短縮",en:"Shortened the tutorial entry flow"}, summary:{ja:"初心者ボタンから確認後、対戦設定を挟まず直接チュートリアルを開始。",en:"The beginner button now starts the tutorial directly after one confirmation."}, details:{ja:["ボタンを押した場所で即座に開始確認を表示","YESから実戦形式チュートリアルへ直接移動","開いているマニュアルや設定が導線を妨げないよう整理"],en:["Shows confirmation immediately","Starts live-match training directly after YES","Closes overlapping Manual or Settings panels"]} },
  { version:"1.0.54", date:"2026-09-07", tags:["BUG FIX","UI","SYSTEM"], title:{ja:"実戦画面チュートリアルへ刷新",en:"Rebuilt tutorial on the live match UI"}, summary:{ja:"通常の対戦画面とゲーム性を保ったまま、AEQRISの説明と強調表示を重ねる方式へ変更。",en:"Tutorial guidance now overlays the real match UI without replacing or over-restricting gameplay."}, details:{ja:["専用の簡易盤を廃止し通常戦と同じ盤面・HUD・操作を使用","合法手を制限せず推奨手だけを強調","前進・横移動・後退や爆風結果に応じて説明を分岐","右上の遊び方と初心者導線を並べて配置","ボーナス移動の説明を遊び方・マニュアル・詳細ガイドへ追加"],en:["Uses the real board, HUD, and controls","Keeps every legal action available while highlighting suggestions","Adapts guidance to movement and blast outcomes","Places Tutorial beside the top-right Manual control","Documents the last-meteor bonus move throughout the guides"]} },
  { version:"1.0.53", date:"2026-09-07", tags:["UI","SYSTEM"], title:{ja:"分岐型チュートリアルを追加",en:"Added an adaptive tutorial"}, summary:{ja:"AEQRISの案内で移動・爆風・大メテオ・CORE到達を実際に体験できる初心者訓練を追加。",en:"Added hands-on AEQRIS training for movement, blast travel, large meteors, and CORE arrival."}, details:{ja:["あそびかた横の初心者マークから開始","前進・横移動など最初の選択に応じて案内を分岐","小メテオの斜め爆風移動と大メテオを実操作","練習CPUはプレイヤーより先にゴールしない","完了後はホーム画面へ安全に復帰"],en:["Starts from the beginner mark beside How to Play","Adapts guidance to the player's opening move","Provides hands-on small and large meteor practice","Training CPU never reaches the CORE first","Returns safely to the home screen"]} },
  { version:"1.0.52", date:"2026-09-02", tags:["BUG FIX","UI"], title:{ja:"PULSE脱出判断と規約名を改善",en:"Improved PULSE escape and policy naming"}, summary:{ja:"CPUがメテオ爆風によるPULSE脱出も判断し、統合ページ名を利用規約へ変更。",en:"CPU now considers meteor-blast PULSE escapes; the combined legal page has a clearer name."}, details:{ja:["通常メテオによるPULSE範囲外への脱出を優先評価","BLASTとメテオの有効な脱出手を同じ判断候補で比較","サイトポリシーの表示名を利用規約へ変更","プライバシー方針は利用規約内に維持"],en:["Prioritizes valid meteor-blast escapes from PULSE","Compares BLAST and meteor escape options","Renamed the combined legal page","Keeps privacy policy within the terms page"]} },
  { version:"1.0.51", date:"2026-09-02", tags:["BUG FIX","UI"], title:{ja:"サイトポリシー統合とアイテムAI改善",en:"Unified policy and improved item AI"}, summary:{ja:"法務ページを統合し、PULSE拘束時と1対1アイテム戦のCPU判断を改善。",en:"Unified policy pages and improved duel item AI under PULSE."}, details:{ja:["プライバシーと利用規約をサイトポリシーへ統合","設定内の不要なリンクを削除","PULSE拘束中の無駄なBOOSTER使用を禁止","BLASTによるPULSE脱出を優先評価","設定ヘッダー上部の表示漏れを修正"],en:["Unified privacy and terms into Site Policy","Removed obsolete Settings links","Prevents wasted BOOSTER use while PULSE-locked","Prioritizes BLAST escape from PULSE","Fixed content showing above the Settings header"]} },
  { version:"1.0.50", date:"2026-09-02", tags:["BUG FIX","UI"], title:{ja:"更新履歴のスクロールを修正",en:"Fixed release-history scrolling"}, summary:{ja:"画面の高さにかかわらず、更新履歴を最後までスクロールできるよう修正。",en:"Release history can now scroll fully at every viewport height."}, details:{ja:["PC・スマホで縦スクロールを維持"],en:["Preserved vertical scrolling on desktop and mobile"]} },
  { version:"1.0.49", date:"2026-09-01", tags:["SYSTEM","UI"], title:{ja:"更新履歴を追加",en:"Release history added"}, summary:{ja:"最新3件の更新内容と、全履歴を確認できる画面を追加。",en:"Added recent updates and a complete release-history page."}, details:{ja:["設定画面に最新3件の更新内容を表示","「すべて見る」から過去の更新履歴を確認可能"],en:["Shows the three latest updates in Settings","Adds a complete history page"]} },
  { version:"1.0.48", date:"2026-08-30", tags:["ASSET","UI"], title:{ja:"ファビコンの視認性を改善",en:"Improved favicon visibility"}, summary:{ja:"白背景の公式シンボルを採用し、小さい表示でも見やすく調整。",en:"Uses the official symbol on white for clearer small-size display."}, details:{ja:["白背景版のシンボルへ変更","ブラウザタブでの識別性を改善"],en:["Switched to the white-background symbol","Improved browser-tab recognition"]} },
  { version:"1.0.47", date:"2026-08-30", tags:["BUG FIX","ASSET"], title:{ja:"ロゴ表示の遅れを解消",en:"Removed logo display delay"}, summary:{ja:"ロゴを事前読込し、画面表示時の一瞬の遅れを解消。",en:"Preloads logos to remove the brief display delay."}, details:{ja:["タイトル・シンボルロゴを事前読込","不要なフェード待ちを削除"],en:["Preloads title and symbol logos","Removed unnecessary fade delay"]} },
  { version:"1.0.46", date:"2026-08-30", tags:["ASSET"], title:{ja:"公式シンボルをファビコンへ反映",en:"Official symbol favicon"}, summary:{ja:"仮アイコンから正式な記号ロゴへ変更。",en:"Replaced the provisional icon with the official symbol."}, details:{ja:["サイトのファビコンを正式ロゴへ統一"],en:["Unified the favicon with the official mark"]} },
  { version:"1.0.45", date:"2026-08-30", tags:["ASSET"], title:{ja:"専用ファビコンを追加",en:"Added a custom favicon"}, summary:{ja:"ブラウザタブ用の専用アイコンを追加。",en:"Added a dedicated browser-tab icon."}, details:{ja:["汎用アイコンから専用アイコンへ変更"],en:["Replaced the generic browser icon"]} },
  { version:"1.0.44", date:"2026-08-30", tags:["BUG FIX","UI"], title:{ja:"PC対戦画面の重なりを修正",en:"Fixed desktop battle overlap"}, summary:{ja:"盤面・操作欄・下部バーを分離し、スクロールなしで収まるよう調整。",en:"Separated board, controls, and footer for a no-scroll desktop layout."}, details:{ja:["メテオ配置欄と盤面の重なりを解消","下部バー用の表示領域を確保","低い画面でも操作できるよう調整"],en:["Cleared meteor controls from the board","Reserved space for the footer","Improved short-screen operation"]} },
  { version:"1.0.43", date:"2026-08-30", tags:["BUG FIX","UI"], title:{ja:"所持品表示を整理",en:"Refined loadout display"}, summary:{ja:"BOOSTERなどの名称と所持数が重ならない2段表示へ変更。",en:"Separated item labels and counts into two rows."}, details:{ja:["アイテム名と数字の重なりを修正","限られた幅での視認性を改善"],en:["Fixed item label/count overlap","Improved narrow-width readability"]} },
  { version:"1.0.42", date:"2026-08-30", tags:["BUG FIX","UI"], title:{ja:"メテオ操作欄の位置を修正",en:"Fixed meteor-control placement"}, summary:{ja:"配置操作が盤面を覆わないようレイアウトを修正。",en:"Adjusted placement controls so they no longer cover the board."}, details:{ja:["誤操作につながる表示の重なりを解消"],en:["Removed overlap that could cause unintended input"]} },
  { version:"1.0.41", date:"2026-08-30", tags:["UI"], title:{ja:"全年齢向けに視認性を向上",en:"Improved all-ages readability"}, summary:{ja:"主要な文字とボタンを大きくし、操作しやすさを改善。",en:"Enlarged key text and controls for easier play."}, details:{ja:["主要ボタンの押しやすさを改善","案内文字のサイズを拡大"],en:["Improved primary button accessibility","Increased guidance text size"]} },
] as const satisfies readonly ReleaseNote[];

export const LATEST_RELEASE_NOTES = RELEASE_NOTES.slice(0, 3);
