export type ReleaseNote = {
  version: string;
  date: string;
  title: { ja: string; en: string };
  summary: { ja: string; en: string };
  details: { ja: readonly string[]; en: readonly string[] };
  tags: readonly ("BUG FIX" | "UI" | "SYSTEM" | "ASSET")[];
};

// 新しいバージョンを先頭へ追加。設定画面には先頭3件だけが表示されます。
export const RELEASE_NOTES = [
  { version:"1.0.78", date:"2026-09-08", tags:["UI","SYSTEM"], title:{ja:"英語表示を全画面へ拡張",en:"Expanded English support across the site"}, summary:{ja:"お問い合わせ、チュートリアル、対戦画面、待機ルーム、利用規約の表示言語を統一。",en:"Unified language switching across contact, tutorial, matches, rooms, and policy pages."}, details:{ja:["チュートリアル全文を日英対応","不具合報告フォームと送信結果を日英対応","対戦HUD・所持欄・チャット・オンライン待機ルームを日英対応","更新履歴と利用規約を端末の表示言語に連動"],en:["Added full Japanese and English tutorial copy","Localized the contact form and submission results","Localized match HUD, inventory, chat, and online rooms","Linked release history and policy pages to the saved display language"]} },
  { version:"1.0.77", date:"2026-09-08", tags:["BUG FIX","SYSTEM"], title:{ja:"CPUのメテオ配置停止を修正",en:"Fixed stalled CPU meteor placement"}, summary:{ja:"手持ちにメテオがある限り、CPUが対戦を止めずに配置。",en:"CPU players now place a meteor whenever one remains available."}, details:{ja:["評価の低い配置でもパスより優先","小メテオがないEASYは大メテオで続行","候補外に空きマスがある場合は盤面全体から探索"],en:["Prioritizes any legal placement over passing","EASY uses a large meteor when no small meteor remains","Scans the full board when sampled candidates are occupied"]} },
  { version:"1.0.76", date:"2026-09-08", tags:["BUG FIX"], title:{ja:"CPU手番中の盤面操作を修正",en:"Fixed board input during CPU turns"}, summary:{ja:"チュートリアル自由対戦中の操作対象を正しく制限。",en:"Corrected input ownership during tutorial free play."}, details:{ja:["CPUの移動・メテオ配置中は盤面入力を無効化"],en:["Disables player board input during CPU movement and meteor placement"]} },
  { version:"1.0.75", date:"2026-09-08", tags:["UI","SYSTEM"], title:{ja:"オンライン待機ルームを改善",en:"Improved the online waiting room"}, summary:{ja:"AI設定とチャットをコンパクトで安全な操作へ調整。",en:"Refined AI settings and chat for safer, more compact operation."}, details:{ja:["AI難易度を人数操作の左側へ移動","10回送信後に10秒間のチャット待機を追加","新着チャットを右下へ表示","メンバー入れ替えをルームリーダー限定に変更","更新履歴を別タブで表示"],en:["Moved AI difficulty to the left of member count controls","Adds a 10-second chat cooldown after ten messages","Shows new chat previews at the lower right","Restricts member swaps to the room leader","Opens release history in a separate tab"]} },
  { version:"1.0.74", date:"2026-09-08", tags:["BUG FIX","SYSTEM"], title:{ja:"オンライン戦の安定性を改善",en:"Improved online match stability"}, summary:{ja:"ホスト端末に集中していた同期とCPU処理の負荷を抑制。",en:"Reduced synchronization and CPU load concentrated on the room host."}, details:{ja:["盤面同期の重複実行を防止","AIの無効なメテオ配置による進行停止を防止","オンラインAIの実行間隔に安全な下限を追加","チーム変更をルームリーダー限定に変更"],en:["Prevents overlapping board synchronization","Prevents invalid AI meteor placement from stalling a match","Adds a safe minimum interval for online AI actions","Restricts team changes to the room leader"]} },
  { version:"1.0.73", date:"2026-09-07", tags:["UI","SYSTEM"], title:{ja:"オンラインルームを拡張",en:"Expanded online rooms"}, summary:{ja:"最大10人の参加と、全員に伝わる対戦設定表示へ改善。",en:"Online rooms now support 10 members and shared match settings."}, details:{ja:["対戦席は最大4人","5人目以降は自動で観戦","観戦者もルームチャットに参加可能","チーム戦・アイテム戦・盤面・CPU人数を全員へ同期表示","閉じているチャットへ未読件数と新着吹き出しを表示"],en:["Up to four active players","Members after the fourth automatically spectate","Spectators can use room chat","Team, item, board, and CPU settings are visible to everyone","Shows unread counts and message previews while chat is closed"]} },
  { version:"1.0.72", date:"2026-09-07", tags:["BUG FIX","UI","SYSTEM"], title:{ja:"対戦ルールと進行を改善",en:"Improved battle rules and flow"}, summary:{ja:"アイテム操作とボーナス行動、オンライン対戦後の流れを改善。",en:"Improved item controls, bonus actions, and the online post-match flow."}, details:{ja:["SHIELDは爆風移動を1マス軽減","ORBITに180度回転を追加","ボーナス行動で移動かアイテムを選択可能","配置しないを選択欄の最後へ移動","オンライン対戦後はマッチルームへ復帰"],en:["SHIELD reduces blast movement by one cell","Added 180-degree ORBIT rotation","Bonus actions can use movement or an item","Moved skip placement to the end","Returns online players to the match room after each battle"]} },
  { version:"1.0.71", date:"2026-09-07", tags:["SYSTEM","UI"], title:{ja:"複数人戦の進行を改善",en:"Improved multiplayer flow"}, summary:{ja:"対戦終了を短縮し、オンラインルーム内の導線を整理。",en:"Shortened match endings and simplified online room navigation."}, details:{ja:["AIだけの対戦継続を省略","残り順位を自動確定","オンラインルーム内のチュートリアルを非表示"],en:["Skips AI-only match continuation","Automatically determines remaining ranks","Hides tutorial access inside online rooms"]} },
  { version:"1.0.70", date:"2026-09-07", tags:["SYSTEM"], title:{ja:"アクセス解析を導入",en:"Added site analytics"}, summary:{ja:"ゲーム体験の改善に役立てるアクセス解析を導入。",en:"Added analytics to help improve the game experience."}, details:{ja:["Google Analyticsに対応","利用規約の案内を更新"],en:["Added Google Analytics support","Updated the privacy notice"]} },
  { version:"1.0.69", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"対戦表示を安定化",en:"Stabilized match presentation"}, summary:{ja:"盤面とCORE到達表示、各画面の操作ボタンを改善。",en:"Improved the board, CORE arrival flow, and screen controls."}, details:{ja:["操作中の盤面サイズを固定","チュートリアルの完了表示を修正","CORE到達後の待ち時間を調整","閉じるボタンの位置を統一"],en:["Keeps the board size fixed during actions","Fixed tutorial completion","Adjusted the delay after reaching the CORE","Aligned close controls consistently"]} },
  { version:"1.0.68", date:"2026-09-07", tags:["SYSTEM","UI"], title:{ja:"可変レイアウトを強化",en:"Improved adaptive layout"}, summary:{ja:"画面や文字の大きさに合わせて盤面が自動調整されるよう改善。",en:"The board now adapts to the available screen and text size."}, details:{ja:["操作欄を含む表示領域へ自動追従"],en:["Adapts to the play area and action controls"]} },
  { version:"1.0.67", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"通常戦の盤面位置を修正",en:"Fixed classic board alignment"}, summary:{ja:"通常戦の盤面を上下中央へ正確に配置。",en:"Precisely centered the classic board vertically."}, details:{ja:["画面上下の余白を均等化"],en:["Balanced the space above and below the board"]} },
  { version:"1.0.66", date:"2026-09-07", tags:["UI"], title:{ja:"盤面の上下余白を調整",en:"Adjusted board spacing"}, summary:{ja:"通常戦とアイテム戦に合わせて盤面位置を調整。",en:"Refined board placement for classic and item matches."}, details:{ja:["画面サイズ別の余白を調整"],en:["Adjusted spacing by screen size"]} },
  { version:"1.0.65", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"案内とチャット表示を修正",en:"Fixed guidance and chat display"}, summary:{ja:"自由対戦中の案内とオンラインチャットの表示を整理。",en:"Refined free-play guidance and online chat presentation."}, details:{ja:["チュートリアルボタンの形を統一","チャット欄を右下へ配置"],en:["Unified the tutorial button shape","Moved chat to the lower right"]} },
  { version:"1.0.64", date:"2026-09-07", tags:["UI","BUG FIX"], title:{ja:"チュートリアル表示を改善",en:"Improved tutorial presentation"}, summary:{ja:"導線を統一し、CPUの行動を見やすく調整。",en:"Unified tutorial access and improved CPU action visibility."}, details:{ja:["案内表示を整理"],en:["Refined tutorial guidance"]} },
  { version:"1.0.63", date:"2026-09-07", tags:["SYSTEM","BUG FIX"], title:{ja:"練習CPUとEASYを調整",en:"Refined training and EASY CPU"}, summary:{ja:"案内中の動きとEASYの判断を安定化。",en:"Stabilized guided actions and EASY decisions."}, details:{ja:["分かりやすい判断を優先"],en:["Prioritizes understandable decisions"]} },
  { version:"1.0.62", date:"2026-09-07", tags:["SYSTEM"], title:{ja:"EASYのメテオ選択を調整",en:"Adjusted EASY meteor choices"}, summary:{ja:"EASYでは小メテオだけを使用するよう調整。",en:"EASY now uses small meteors only."}, details:{ja:["難易度ごとの特徴を明確化"],en:["Clarified the difficulty levels"]} },
  { version:"1.0.61", date:"2026-09-07", tags:["BUG FIX","SYSTEM"], title:{ja:"チュートリアルCPUを修正",en:"Fixed the tutorial CPU"}, summary:{ja:"練習を最後まで進められるよう調整。",en:"Training can now always be completed."}, details:{ja:["CPUの勝利条件を調整"],en:["Adjusted the CPU win condition"]} },
  { version:"1.0.60", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"チュートリアル開始確認を修正",en:"Fixed tutorial confirmation"}, summary:{ja:"各画面で開始確認がすぐ表示されるよう修正。",en:"Tutorial confirmation now appears immediately across screens."}, details:{ja:["開始確認の表示を安定化"],en:["Stabilized the start confirmation"]} },
  { version:"1.0.59", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"チュートリアル進行を調整",en:"Refined tutorial timing"}, summary:{ja:"説明と相手の行動が順番に進むよう調整。",en:"Tutorial guidance and opponent actions now proceed in sequence."}, details:{ja:["説明中は盤面を停止"],en:["Pauses the board during guidance"]} },
  { version:"1.0.58", date:"2026-09-07", tags:["BUG FIX","UI"], title:{ja:"チュートリアル入口を修正",en:"Fixed tutorial access"}, summary:{ja:"各準備画面からチュートリアルを開始可能に。",en:"Tutorial access is now available from preparation screens."}, details:{ja:["案内表現を統一"],en:["Unified guidance wording"]} },
  { version:"1.0.57", date:"2026-09-07", tags:["UI"], title:{ja:"案内文を調整",en:"Refined tutorial guidance"}, summary:{ja:"AEQRISの案内を自然な表現に調整。",en:"Refined AEQRIS tutorial guidance."}, details:{ja:["現在のルールを簡潔に案内"],en:["Presents the current rules concisely"]} },
  { version:"1.0.56", date:"2026-09-07", tags:["UI","BUG FIX"], title:{ja:"チュートリアル入口を全画面へ統一",en:"Unified tutorial access across screens"}, summary:{ja:"オンライン対戦中を除き、ホーム・対戦設定・通常対戦画面からすぐ開始確認を表示。",en:"Tutorial confirmation is now available from home, setup, and offline match screens."}, details:{ja:["確認文を「チュートリアルを開始しますか？」だけに簡略化","YESからチュートリアルへ直接移動","オフライン対戦画面の右上にも初心者ボタンを追加","オンライン待機室からは正常に退出して開始","進行中のオンライン対戦ではボタンを非表示"],en:["Simplified the confirmation prompt","Starts directly after YES","Added the beginner button to offline matches","Leaves online waiting rooms cleanly before training","Hides the button during active online matches"]} },
  { version:"1.0.55", date:"2026-09-07", tags:["UI","BUG FIX"], title:{ja:"チュートリアル導線を短縮",en:"Shortened the tutorial entry flow"}, summary:{ja:"初心者ボタンから確認後、対戦設定を挟まず直接チュートリアルを開始。",en:"The beginner button now starts the tutorial directly after one confirmation."}, details:{ja:["ボタンを押した場所で即座に開始確認を表示","YESから実戦形式チュートリアルへ直接移動","開いているマニュアルや設定が導線を妨げないよう整理"],en:["Shows confirmation immediately","Starts live-match training directly after YES","Closes overlapping Manual or Settings panels"]} },
  { version:"1.0.54", date:"2026-09-07", tags:["BUG FIX","UI","SYSTEM"], title:{ja:"実戦画面チュートリアルへ刷新",en:"Rebuilt tutorial on the live match UI"}, summary:{ja:"通常の対戦画面とゲーム性を保ったまま、AEQRISの説明と強調表示を重ねる方式へ変更。",en:"Tutorial guidance now overlays the real match UI without replacing or over-restricting gameplay."}, details:{ja:["専用の簡易盤を廃止し通常戦と同じ盤面・HUD・操作を使用","合法手を制限せず推奨手だけを強調","前進・横移動・後退や爆風結果に応じて説明を分岐","右上の遊び方と初心者導線を並べて配置","ボーナス移動の説明を遊び方・マニュアル・詳細ガイドへ追加","全モード・人数構成63試合のシミュレーションを完走"],en:["Uses the real board, HUD, and controls","Keeps every legal action available while highlighting suggestions","Adapts guidance to movement and blast outcomes","Places Tutorial beside the top-right Manual control","Documents the last-meteor bonus move throughout the guides","Completed 63 simulated matches across all supported modes"]} },
  { version:"1.0.53", date:"2026-09-07", tags:["UI","SYSTEM"], title:{ja:"分岐型チュートリアルを追加",en:"Added an adaptive tutorial"}, summary:{ja:"AEQRISの案内で移動・爆風・大メテオ・CORE到達を実際に体験できる初心者訓練を追加。",en:"Added hands-on AEQRIS training for movement, blast travel, large meteors, and CORE arrival."}, details:{ja:["あそびかた横の初心者マークから開始","前進・横移動など最初の選択に応じて案内を分岐","小メテオの斜め爆風移動と大メテオを実操作","練習CPUはプレイヤーより先にゴールしない","完了後はホーム画面へ安全に復帰"],en:["Starts from the beginner mark beside How to Play","Adapts guidance to the player's opening move","Provides hands-on small and large meteor practice","Training CPU never reaches the CORE first","Returns safely to the home screen"]} },
  { version:"1.0.52", date:"2026-09-02", tags:["BUG FIX","UI"], title:{ja:"PULSE脱出判断と規約名を改善",en:"Improved PULSE escape and policy naming"}, summary:{ja:"CPUがメテオ爆風によるPULSE脱出も判断し、統合ページ名を利用規約へ変更。",en:"CPU now considers meteor-blast PULSE escapes; the combined legal page has a clearer name."}, details:{ja:["通常メテオによるPULSE範囲外への脱出を優先評価","BLASTとメテオの有効な脱出手を同じ判断候補で比較","サイトポリシーの表示名を利用規約へ変更","プライバシー方針は利用規約内に維持"],en:["Prioritizes valid meteor-blast escapes from PULSE","Compares BLAST and meteor escape options","Renamed the combined legal page","Keeps privacy policy within the terms page"]} },
  { version:"1.0.51", date:"2026-09-02", tags:["BUG FIX","UI"], title:{ja:"サイトポリシー統合とアイテムAI改善",en:"Unified policy and improved item AI"}, summary:{ja:"法務ページを統合し、PULSE拘束時と1対1アイテム戦のCPU判断を改善。",en:"Unified policy pages and improved duel item AI under PULSE."}, details:{ja:["プライバシーと利用規約をサイトポリシーへ統合","設定内の不要なリンクを削除","PULSE拘束中の無駄なBOOSTER使用を禁止","BLASTによるPULSE脱出を優先評価","設定ヘッダー上部の表示漏れを修正"],en:["Unified privacy and terms into Site Policy","Removed obsolete Settings links","Prevents wasted BOOSTER use while PULSE-locked","Prioritizes BLAST escape from PULSE","Fixed content showing above the Settings header"]} },
  { version:"1.0.50", date:"2026-09-02", tags:["BUG FIX","UI"], title:{ja:"更新履歴のスクロールを修正",en:"Fixed release-history scrolling"}, summary:{ja:"画面の高さにかかわらず、更新履歴を最後までスクロールできるよう修正。",en:"Release history can now scroll fully at every viewport height."}, details:{ja:["対戦画面専用のスクロール固定から文書ページを除外","PC・スマホで縦スクロールを維持"],en:["Excluded document pages from the battle viewport lock","Preserved vertical scrolling on desktop and mobile"]} },
  { version:"1.0.49", date:"2026-09-01", tags:["SYSTEM","UI"], title:{ja:"更新履歴を追加",en:"Release history added"}, summary:{ja:"最新3件の更新内容と、全履歴を確認できる画面を追加。",en:"Added recent updates and a complete release-history page."}, details:{ja:["設定画面に最新3件の更新内容を表示","「すべて見る」から過去の更新履歴を確認可能","更新内容を1ファイルで管理できる構成へ整理"],en:["Shows the three latest updates in Settings","Adds a complete history page","Centralizes release notes in one file"]} },
  { version:"1.0.48", date:"2026-08-30", tags:["ASSET","UI"], title:{ja:"ファビコンの視認性を改善",en:"Improved favicon visibility"}, summary:{ja:"白背景の公式シンボルを採用し、小さい表示でも見やすく調整。",en:"Uses the official symbol on white for clearer small-size display."}, details:{ja:["白背景版のシンボルへ変更","ブラウザタブでの識別性を改善"],en:["Switched to the white-background symbol","Improved browser-tab recognition"]} },
  { version:"1.0.47", date:"2026-08-30", tags:["BUG FIX","ASSET"], title:{ja:"ロゴ表示の遅れを解消",en:"Removed logo display delay"}, summary:{ja:"ロゴを事前読込し、画面表示時の一瞬の遅れを解消。",en:"Preloads logos to remove the brief display delay."}, details:{ja:["タイトル・シンボルロゴを事前読込","不要なフェード待ちを削除"],en:["Preloads title and symbol logos","Removed unnecessary fade delay"]} },
  { version:"1.0.46", date:"2026-08-30", tags:["ASSET"], title:{ja:"公式シンボルをファビコンへ反映",en:"Official symbol favicon"}, summary:{ja:"仮アイコンから正式な記号ロゴへ変更。",en:"Replaced the provisional icon with the official symbol."}, details:{ja:["サイトのファビコンを正式ロゴへ統一"],en:["Unified the favicon with the official mark"]} },
  { version:"1.0.45", date:"2026-08-30", tags:["ASSET"], title:{ja:"専用ファビコンを追加",en:"Added a custom favicon"}, summary:{ja:"ブラウザタブ用の専用アイコンを追加。",en:"Added a dedicated browser-tab icon."}, details:{ja:["汎用アイコンから専用アイコンへ変更"],en:["Replaced the generic browser icon"]} },
  { version:"1.0.44", date:"2026-08-30", tags:["BUG FIX","UI"], title:{ja:"PC対戦画面の重なりを修正",en:"Fixed desktop battle overlap"}, summary:{ja:"盤面・操作欄・下部バーを分離し、スクロールなしで収まるよう調整。",en:"Separated board, controls, and footer for a no-scroll desktop layout."}, details:{ja:["メテオ配置欄と盤面の重なりを解消","下部バー用の表示領域を確保","低い画面でも操作できるよう調整"],en:["Cleared meteor controls from the board","Reserved space for the footer","Improved short-screen operation"]} },
  { version:"1.0.43", date:"2026-08-30", tags:["BUG FIX","UI"], title:{ja:"所持品表示を整理",en:"Refined loadout display"}, summary:{ja:"BOOSTERなどの名称と所持数が重ならない2段表示へ変更。",en:"Separated item labels and counts into two rows."}, details:{ja:["アイテム名と数字の重なりを修正","限られた幅での視認性を改善"],en:["Fixed item label/count overlap","Improved narrow-width readability"]} },
  { version:"1.0.42", date:"2026-08-30", tags:["BUG FIX","UI"], title:{ja:"メテオ操作欄の位置を修正",en:"Fixed meteor-control placement"}, summary:{ja:"配置操作が盤面を覆わないようレイアウトを修正。",en:"Adjusted placement controls so they no longer cover the board."}, details:{ja:["誤操作につながる表示の重なりを解消"],en:["Removed overlap that could cause unintended input"]} },
  { version:"1.0.41", date:"2026-08-30", tags:["UI"], title:{ja:"全年齢向けに視認性を向上",en:"Improved all-ages readability"}, summary:{ja:"主要な文字とボタンを大きくし、操作しやすさを改善。",en:"Enlarged key text and controls for easier play."}, details:{ja:["主要ボタンの押しやすさを改善","案内文字のサイズを拡大"],en:["Improved primary button accessibility","Increased guidance text size"]} },
] as const satisfies readonly ReleaseNote[];

export const LATEST_RELEASE_NOTES = RELEASE_NOTES.slice(0, 3);
