/** 画面上の文章を編集する場所です。キーは変更せず、ja/enの文章だけを編集してください。 */
export const UI_COPY = {
  titleAria: { ja: "METEOR RACE タイトル画面", en: "METEOR RACE title screen" },
  manualLabel: { ja: "あそびかた", en: "MANUAL" },
  gameStart: { ja: "ゲーム開始", en: "GAME START" },
  settingsLabel: { ja: "設定", en: "SETTINGS" },
  privacyLabel: { ja: "プライバシー", en: "PRIVACY" },
  onlineReady: { ja: "オンライン対応", en: "ONLINE READY" },
  guestPlayer: { ja: "ゲスト", en: "GUEST PLAYER" },
  ruleGuide: { ja: "ルール案内", en: "RULE GUIDE" },
  howToPlay: { ja: "あそびかた", en: "HOW TO PLAY" },
  playStyle: { ja: "プレイ方法", en: "PLAY STYLE" },
  round: { ja: "ラウンド", en: "ROUND" },
  languageHeading: { ja: "言語", en: "LANGUAGE" },
  japaneseLanguage: { ja: "日本語", en: "Japanese" },
  englishLanguage: { ja: "英語", en: "English" },
  accountHeading: { ja: "プレイヤー", en: "ACCOUNT" },
  soundHeading: { ja: "サウンド", en: "SOUND" },
  displayHeading: { ja: "表示", en: "DISPLAY" },
  contactHeading: { ja: "お問い合わせ", en: "CONTACT" },
  turnLoopHeading: { ja: "手番の流れ", en: "TURN LOOP" },
  itemArchiveHeading: { ja: "アイテム", en: "ITEM ARCHIVE" },
  openManual: { ja: "マニュアルを開く", en: "Open manual" },
  closeManual: { ja: "マニュアルを閉じる", en: "Close manual" },
  titleDescription: {
    ja: "メテオの爆風でCOREを目指す、登録・インストール不要の無料オンライン戦略ボードゲームです。CPU戦と2〜4人対戦に対応しています。",
    en: "An online strategy board game where meteor blasts propel you toward the CORE. Play against CPUs or 2–4 players for free, with no account or installation required.",
  },
  titleTagline: { ja: "爆風を味方に、COREを目指せ", en: "BLAST YOUR WAY TO THE CORE" },
  choosePlayStyle: { ja: "プレイ方法を選択", en: "Choose how to play" },
  chooseOpponent: { ja: "誰と遊ぶかを選んでください。", en: "Choose who you want to play with." },
  cpuBattle: { ja: "CPUと対戦", en: "Play against CPUs" },
  localBattle: { ja: "同じ端末で対戦", en: "Share this device" },
  onlineBattle: { ja: "通信対戦", en: "Play online" },
  next: { ja: "次へ", en: "NEXT" },
  leaveRoom: { ja: "← ルーム退出", en: "← LEAVE ROOM" },
  lobby: { ja: "← 待機ルーム", en: "← LOBBY" },
  leaveMatch: { ja: "← 対戦退出", en: "← LEAVE MATCH" },
  back: { ja: "← 戻る", en: "← BACK" },
  settings: { ja: "設定", en: "Settings" },
  closeSettings: { ja: "設定を閉じる", en: "Close settings" },
  displayLanguage: { ja: "表示言語", en: "Display language" },
  languageSaved: { ja: "表示言語はこの端末に保存されます。", en: "Your language choice is saved on this device." },
  nickname: { ja: "ニックネーム", en: "Nickname" },
  autoSave: { ja: "入力すると自動保存されます", en: "Changes are saved automatically." },
  accountType: { ja: "アカウント方式", en: "Account type" },
  accountNote: {
    ja: "メールアドレス登録はありません。ニックネームとPLAYER IDはこの端末に保存され、他のプレイヤーにはニックネームだけが表示されます。対戦中の変更は次の試合から反映されます。",
    en: "No email registration is required. Your nickname and PLAYER ID are stored on this device; only your nickname is shown to other players. Changes made during a match apply from the next match.",
  },
  masterVolume: { ja: "全体音量", en: "Master volume" },
  soundEffects: { ja: "効果音", en: "Sound effects" },
  muteAll: { ja: "一括ミュート", en: "Mute all" },
  reduceMotion: { ja: "演出短縮", en: "Reduce motion" },
  rulesAndItems: { ja: "ルール・アイテム一覧", en: "Rules & Items" },
  close: { ja: "閉じる", en: "Close" },
  manualMove: { ja: "探査機を縦横へ1マス移動", en: "Move your probe one orthogonal cell" },
  manualMeteor: { ja: "小または大メテオを1個配置", en: "Place one small or large meteor" },
  manualItem: { ja: "アイテム戦ではメテオ配置の代わりに使用可能", en: "In ITEM mode, use an item instead of placing a meteor" },
  manualNext: { ja: "↺ 次のプレイヤーのMOVEへ", en: "↺ Continue to the next player's MOVE" },
  noDiagonal: { ja: "※ 斜め移動はできません。", en: "* Diagonal movement is not allowed." },
  blastPropulsion: { ja: "※ BLASTは相手を妨害するだけでなく、自分を進める推進力にもなります。", en: "* BLAST can disrupt rivals or propel your own probe." },
  anyCoreArrival: { ja: "※ 移動・爆風・アイテムのどの方法でもCOREへ入れば到達です。", en: "* Entering CORE by movement, blast, or item counts as arrival." },
  firstTurnRule: { ja: "※ 先攻の最初の手番だけメテオを配置できません。", en: "* The starting player cannot place a meteor on the first turn." },
  selectedItems: { ja: "選択したアイテム", en: "Selected items" },
  emptyLoadout: { ja: "下のアイテムを選ぶと、ここに使用イメージと説明が追加されます。", en: "Choose items below to add their preview and description here." },
  confirm: { ja: "決定", en: "CONFIRM" },
  cancelSelection: { ja: "選択をキャンセル", en: "CANCEL SELECTION" },
  meteorToPlace: { ja: "配置するメテオ", en: "Choose a meteor" },
  smallMeteor: { ja: "小", en: "SMALL" },
  largeMeteor: { ja: "大", en: "LARGE" },
  passPlacement: { ja: "配置しない", en: "PASS" },
  selectItems: { ja: "アイテムを{total}個選択（同じ種類は{same}個まで）", en: "Choose {total} items (up to {same} of the same kind)" },
  selectedCount: { ja: "{count} / {total} 選択済み", en: "{count} / {total} SELECTED" },
  itemEffectAria: { ja: "{kind}の効果情報", en: "{kind} effect information" },
  boardAria: { ja: "{size}×{size} ゲーム盤", en: "{size}×{size} game board" },
  itemUseWarning: { ja: "使用すると、この手番はメテオを配置できません", en: "Using an item replaces meteor placement this turn" },
  chooseOrbitRing: { ja: "ORBIT：盤上の回転させたいリングを選択", en: "ORBIT: choose a ring on the board" },
  chooseOrbitDirection: { ja: "R{ring}：回転方向を選択", en: "R{ring}: choose a rotation direction" },
  clockwise: { ja: "時計回り ↻", en: "CLOCKWISE ↻" },
  counterclockwise: { ja: "反時計回り ↺", en: "COUNTERCLOCKWISE ↺" },
  chooseRingAgain: { ja: "リングを選び直す", en: "CHOOSE ANOTHER RING" },
  chooseBoardTarget: { ja: "{kind}：盤上から対象を選択", en: "{kind}: choose a target on the board" },
  blockedMove: { ja: "移動不能 — メテオ配置へ", en: "NO LEGAL MOVE — CONTINUE TO METEOR" },
  statusSetup: { ja: "{player}：アイテムを選択", en: "{player}: choose your items" },
  statusMove: { ja: "{player}：探査機を1マス移動", en: "{player}: move your probe one cell" },
  statusPlace: { ja: "{player}：メテオまたはアイテムを選択", en: "{player}: place a meteor or use an item" },
  statusSwitch: { ja: "{player}：{kind}の対象を選択", en: "{player}: choose a target for {kind}" },
  statusWinner: { ja: "{player} WIN!", en: "{player} WINS!" },
  statusDraw: { ja: "同時到達 — DRAW", en: "SIMULTANEOUS ARRIVAL — DRAW" },
} as const;

export type UiCopyKey = keyof typeof UI_COPY;
